name: exam-archive deployment

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Prepare version tag
        run: |
          # "refs/tags/v1.2.3" --> "1.2.3" expose as $DOCKER_TAG
          RELEASE_TAG=${GITHUB_REF//refs\/tags\/v}
          [[ ! "${RELEASE_TAG}" =~ '^[0-9]+\.[0-9]+\.[0-9]+$' ]] && exit 1 || echo 'Release tag OK'
          echo "DOCKER_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: Build and push to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        run: |
          docker build -t exam-archive:latest .
          docker tag exam-archive:latest $ECR_REGISTRY/tkoaly/exam-archive:$DOCKER_TAG
          docker push $ECR_REGISTRY/tkoaly/exam-archive:$DOCKER_TAG
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Setup Terraform variables
        run: |
          echo "TF_VAR_aws_profile=default" >> $GITHUB_ENV
          echo "TF_VAR_image_version_tag=$DOCKER_TAG" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          cd ./tf
          terraform init
      - name: Terraform Plan
        run: |
          cd ./tf
          terraform plan -out=plan
      - name: Terraform Apply
        run: |
          cd ./tf
          terraform apply plan